window.QUESTION_DATA = [
  {
    title: "🎈 Light & Playful 🎈",
    items: [
      "{PLAYER}, what daily gesture reveals more about you than you think?",
      "{PLAYER}, what’s your little luxury that makes you smile even on a bad day?",
      "{ALL}, what body part is the funniest to describe without showing it?",
      "{PLAYER}, if you were a summer drink, which one would you be and why?",
      "{PLAYER}, which emoji best describes your energy today?",
      "{PLAYER}, what harmless compliment always makes you a bit shy?",
      "{ALL}, what do you prefer: comfortable silence or light chatter?",
      "{PLAYER}, what tiny detail do you always notice when meeting someone new?",
      "{PLAYER}, what makes you instantly likable to others without trying?",
      "{PLAYER}, what always makes you laugh even when you shouldn’t?",
      "{PLAYER}, what’s the last kind gesture that stuck with you?",
      "{PLAYER}, what sound instantly puts you in a good mood?",
      "{PLAYER}, which color represents you best when you’re nude?",
      "{ALL}, what’s better: a funny slip-up or a perfect compliment?",
      "{PLAYER}, what daily ritual makes you feel at home anywhere?",
      "{PLAYER}, what’s your quirkiest flaw?",
      "{PLAYER}, if you had to teach one gesture you like, which would it be?",
      "{PLAYER}, which part of your body moves the most when you talk?",
      "{PLAYER}, what do you notice first in a smile?",
      "{ALL}, do you prefer loud laughter or stifled laughter?",
      "{PLAYER}, what detail about your voice surprises you when you hear it recorded?",
      "{PLAYER}, what’s the first thing you do to relax among strangers?",
      "{PLAYER}, what simple compliment always feels good to receive?",
      "{PLAYER}, if your body had a funny superpower, what would it be?",
      "{PLAYER}, what gesture seems innocent but is secretly attractive?",
      "{ALL}, what’s more charming: smiling eyes or talking hands?",
      "{PLAYER}, what usually surprises people when they meet you for the first time?",
      "{PLAYER}, if your body could tell one story, what would it be?",
      "{PLAYER}, what word or phrase do you overuse without realizing it?",
      "{PLAYER}, what unusual thing relaxes you the most?",
      "{PLAYER}, what makes you laugh harder: a clumsy move or a failed joke?",
      "{PLAYER}, if you had a theme song when you walk into a room, what would it be?",
      "{PLAYER}, what detail about your appearance changes most often (hair, beard, accessories)?",
      "{ALL}, what’s better: being remembered for a witty line or a tender gesture?",
      "{PLAYER}, what facial expression escapes you when you’re truly engaged in a conversation?",
      "{PLAYER}, what’s the tiniest body movement that betrays your feelings?",
      "{PLAYER}, what do your friends always notice about you that you don’t get?",
      "{ALL}, what’s harder to hide: a smile or a blush?",
      "{PLAYER}, what is the dumbest thing you believed as a kid?",
      "{PLAYER}, what is the weirdest snack combo you actually like?",
      "{PLAYER}, what is the most embarrassing song you still enjoy?",
      "{PLAYER}, what is the funniest thing you ever did by mistake?",
      "{PLAYER}, what is the strangest place you have ever fallen asleep?",
      "{PLAYER}, what is the worst haircut you ever had?",
      "{PLAYER}, what is one silly thing you still do like a child?",
      "{PLAYER}, what is the weirdest food you ever ate?",
      "{PLAYER}, what is the most useless talent you have?",
      "{PLAYER}, what is the funniest thing that made you laugh way too hard?",
      "{PLAYER}, what is the worst excuse you ever gave and got away with?",
      "{PLAYER}, what is the silliest fashion choice you ever made?",
      "{PLAYER}, what is the most random thing you have in your room right now?",
      "{PLAYER}, what is the most awkward thing you ever said to a stranger?",
      "{PLAYER}, what is a TV show or movie you secretly love but won’t admit easily?",
      "{PLAYER}, what is the silliest fear you have?",
      "{PLAYER}, what is the longest time you wore the same clothes?",
      "{PLAYER}, what is the funniest text you ever sent by accident?",
      "{PLAYER}, what is the strangest dream you ever had?",
      "{PLAYER}, what is the weirdest thing you ever Googled?",
      "{PLAYER}, what is the funniest photo of you that exists?",
      "{PLAYER}, what is one thing you are really bad at but still try?",
      "{PLAYER}, what is the worst advice you ever gave?",
      "{PLAYER}, what is the strangest thing you collected as a kid?",
      "{PLAYER}, what is the most awkward thing you did in public?",
      "{PLAYER}, what is the funniest sound you can make?",
      "{PLAYER}, what is the most random lie you ever told?",
      "{PLAYER}, what is the most ridiculous thing you believed from the internet?",
      "{PLAYER}, what is the dumbest argument you ever had?",
      "{PLAYER}, what is the weirdest thing in your bag or pockets right now?",
      "{PLAYER}, what is the laziest thing you ever did?",
      "{PLAYER}, what is one silly superstition you still follow?",
      "{PLAYER}, what is the strangest smell you actually like?",
      "{PLAYER}, what is the most awkward thing you did on camera?",
      "{PLAYER}, what is a habit you know looks funny but you keep doing it?",
      "{PLAYER}, what is the most ridiculous dare you ever accepted?",
      "{PLAYER}, what is the funniest mistake you ever made in English?",
      "{PLAYER}, what is the most useless app on your phone?",
      "{PLAYER}, what is the silliest nickname you ever had?",
      "{PLAYER}, what is the weirdest thing you ever laughed at alone?",
      "{PLAYER}, what’s a small habit that always makes people smile around you?",
      "{PLAYER}, what’s the funniest misunderstanding you’ve ever had?",
      "{PLAYER}, what’s the most random thing that can make your day better?",
      "{ALL}, what’s the weirdest way you’ve seen someone celebrate something?",
      "{PLAYER}, what’s a sound that instantly makes you laugh?",
      "{PLAYER}, what’s your go-to funny excuse when you’re late?",
      "{PLAYER}, what’s the most unnecessary skill you’ve mastered?",
      "{PLAYER}, what simple thing turns into chaos when you do it?",
      "{PLAYER}, what’s the most random compliment you’ve ever received?",
      "{PLAYER}, what’s the most unexpected thing you’re good at?",
      "{PLAYER}, what’s your favorite completely useless fact?",
      "{PLAYER}, what’s the silliest thing you believed was true for years?",
      "{ALL}, what’s something everyone has done at least once but never admits?",
      "{PLAYER}, what’s your weirdest ritual before sleeping?",
      "{PLAYER}, what’s the most ridiculous rule you’ve ever made for yourself?",
      "{PLAYER}, what’s your funniest accidental talent?",
      "{PLAYER}, what everyday object would be the worst to explain to aliens?",
      "{PLAYER}, what’s the strangest thing you’ve ever named?",
      "{PLAYER}, what’s your secret recipe for cheering yourself up?",
      "{PLAYER}, what’s the most random thought that popped into your head today?",
      "{ALL}, if you all had to invent a new holiday, what would it celebrate?",
      "{PLAYER}, what’s a silly habit you can’t give up?",
      "{PLAYER}, what’s the most random sound you can make right now?",
      "{PLAYER}, what’s your go-to move when something awkward happens?",
      "{PLAYER}, what’s the funniest typo you’ve ever sent?",
      "{PLAYER}, what’s your weirdest late-night craving that isn’t food?",
      "{PLAYER}, what’s the oddest compliment you’ve given someone?",
      "{PLAYER}, what’s your personal theme song for doing chores?",
      "{ALL}, what’s the funniest thing to overhear in a public place?",
      "{PLAYER}, what’s the weirdest thing that ever made you feel proud?",
      "{PLAYER}, what’s the most ridiculous rumor you’ve heard about yourself?",
      "{PLAYER}, what’s your favorite tiny victory move?",
      "{PLAYER}, what’s the most surprising thing that always makes you laugh?",
      "{PLAYER}, what’s a thing you do that always feels like a mini victory?",
      "{PLAYER}, what’s the most random item you’ve ever found in your pocket?",
      "{PLAYER}, what’s something completely normal that freaks you out?",
      "{PLAYER}, what’s the funniest face you’ve ever made on purpose?",
      "{ALL}, what’s something weirdly satisfying that everyone secretly enjoys?"
    ]
  },
  {
    title: "💌 Flirty & Personal 🌹",
    items: [
      "{PLAYER}, what small compliment always feels special to you?",
      "{PLAYER}, which tone of voice makes you feel instantly comfortable?",
      "{PLAYER}, what kind of praise do you never get tired of hearing?",
      "{PLAYER}, what little gesture makes you feel seen in a group?",
      "{PLAYER}, what quality do you think makes people curious about you?",
      "{PLAYER}, which type of smile makes you feel warm: quick grin or slow build?",
      "{PLAYER}, what makes you blush faster: words or eye contact?",
      "{PLAYER}, what kind of humor always wins you over?",
      "{PLAYER}, what’s a subtle way you show interest in people?",
      "{PLAYER}, which do you find harder to hide: curiosity or attraction?",
      "{ALL}, what’s more memorable: a gentle compliment or playful teasing?",
      "{PLAYER}, what detail about your vibe would surprise others?",
      "{PLAYER}, what’s your favorite way to greet someone new?",
      "{PLAYER}, which moment in conversation makes you feel closest to others?",
      "{PLAYER}, what compliment would you like to give yourself tonight?",
      "{PLAYER}, what’s your favorite way to make someone feel included?",
      "{PLAYER}, what word do you secretly love hearing about yourself?",
      "{PLAYER}, what type of compliment feels more honest: about looks or about character?",
      "{PLAYER}, which body language signal do you notice first in others?",
      "{PLAYER}, what makes a compliment unforgettable for you?",
      "{PLAYER}, which do you value more: being admired or being understood?",
      "{PLAYER}, what’s the simplest thing someone can do to make you smile?",
      "{PLAYER}, what part of connection matters more to you: words or timing?",
      "{PLAYER}, what makes you feel instantly closer to a stranger?",
      "{PLAYER}, which do you notice first: someone’s eyes, voice, or rhythm?",
      "{PLAYER}, what quality do you most enjoy highlighting in others?",
      "{PLAYER}, which is more powerful: being remembered or being missed?"
    ]
  },
  {
    title: "🔥 Spicy & Suggestive 👀",
    items: [
      "{PLAYER}, what kind of look in the eyes makes you feel a spark?",
      "{PLAYER}, what is hotter: a look that stays or a smile that fades?",
      "{PLAYER}, what small move feels stronger than words?",
      "{PLAYER}, what feels more bold: sitting close or leaning in?",
      "{PLAYER}, what do your hands do when you feel shy but excited?",
      "{PLAYER}, what silence feels stronger: long or sudden?",
      "{PLAYER}, what is stronger: a touch by mistake or a long stare?",
      "{PLAYER}, if you had only body language, how would you show interest?",
      "{PLAYER}, what’s the first sign someone makes your heart beat faster?",
      "{PLAYER}, what makes a whisper hotter: the word or the tone?",
      "{PLAYER}, what type of tension do you like more: playful or serious?",
      "{PLAYER}, what small compliment feels almost too much to say?",
      "{ALL}, what feels sexier: a pause before words or fast replies?",
      "{PLAYER}, what’s your signal when chemistry is growing?",
      "{PLAYER}, what feels braver: holding eye contact or breaking it slowly?",
      "{PLAYER}, if you had to invent a “signal” of attraction, what would it be?",
      "{PLAYER}, what’s more fun: teasing with words or being close in space?",
      "{PLAYER}, how do you know when play turns into flirting?",
      "{PLAYER}, what makes you feel more nervous: being watched or ignored?",
      "{PLAYER}, how do you hide it when you stare too much?",
      "{PLAYER}, what feels more close: sharing a secret or sharing a look?",
      "{PLAYER}, what part of body language is hardest to fake?",
      "{PLAYER}, what makes you feel more open: standing close or a deep question?",
      "{PLAYER}, what’s your favorite way to raise tension playfully?",
      "{PLAYER}, what small move makes a moment feel charged?",
      "{PLAYER}, what is more suggestive: a hand on the table or under it?",
      "{PLAYER}, what kind of stare makes you feel caught?",
      "{PLAYER}, what timing makes a moment unforgettable?",
      "{PLAYER}, what’s one thing you always find attractive at first sight?"
    ]
  },
  {
    title: "🍑 Explicit & Erotic 💦",
    items: [
      "{PLAYER}, what is the first part of a naked body you notice?",
      "{PLAYER}, do you like more playful control or strong control in bed?",
      "{PLAYER}, what secret turn-on have you never told anyone?",
      "{PLAYER}, what dirty compliment would hit you the hardest right now?",
      "{PLAYER}, what part of dirty talk makes you lose control faster: orders, praise, or filthy words?",
      "{PLAYER}, how do you like to start foreplay: touch, words, or both?",
      "{PLAYER}, what would you want whispered in your ear right before you cum?",
      "{PLAYER}, what sex position would you want to try?",
      "{PLAYER}, what dirty roleplay would you want to try?",
      "{PLAYER}, be honest, do you prefer cut or uncut? Explain why.",
      "{PLAYER}, what sex toy do you wish you had right now?",
      "{PLAYER}, what fetish would you be curious to explore?",
      "{PLAYER}, what is hotter: rough passion or slow torment?",
	  "{PLAYER}, What does it feel like and where do you feel it, when you're the most turned on you can be?",
	  "{PLAYER}, Do you have a spot on your body that instantly increases your arousal?",
	  "{PLAYER}, Describe (or demonstrate with a toy) your favorite technique for giving a blow job."
    ]
  },
  {
    title: "🌌 Deep & Intimate 💭",
    items: [
      "{PLAYER}, what makes being naked exciting instead of awkward for you?",
      "{PLAYER}, what part of your body feels the most shy to show?",
      "{PLAYER}, what kind of silence feels good instead of strange?",
      "{PLAYER}, what compliment about your body would mean the most from someone?",
      "{PLAYER}, what is your favorite part of being close with someone who is not a partner?",
      "{PLAYER}, what fantasy works better with a lover than with a friend?",
      "{PLAYER}, if you had a secret code word for “I feel horny,” what would it be?",
      "{PLAYER}, what thought always flashes in your head when you undress with others?",
      "{PLAYER}, what is the hottest part of sharing cam time with someone you trust?",
      "{PLAYER}, what insecurity disappears when you are naked with friends?",
      "{PLAYER}, when was the last time you got turned on just by thinking of someone in this room?",
      "{PLAYER}, what secret kink feels easier to admit here than with a partner?",
      "{PLAYER}, what is one dirty joke you wanted to tell but held back?",
      "{PLAYER}, what does “being seen naked” mean to you?",
      "{PLAYER}, what part of sex with friends feels better than with lovers?",
      "{PLAYER}, what makes you smile even when you are aroused?",
      "{PLAYER}, what is one fantasy you would only share here and not outside?",
      "{PLAYER}, what do you think is the sexiest thing about falling asleep next to someone?",
      "{PLAYER}, what after-moment ritual would make you feel cared for?",
      "{PLAYER}, what is one secret about your desires you would only admit here?",
      "{PLAYER}, what makes the tension stronger: laughing or moaning?",
      "{PLAYER}, what makes you feel closer: long eye contact or a soft touch?",
      "{PLAYER}, what part of your body do you want more praise for?",
      "{PLAYER}, what’s the most intimate non-sexual thing someone can do with you?",
      "{PLAYER}, what rule would you set to keep this exciting but safe?",
      "{PLAYER}, what kind of attention makes you feel completely desired?",
      "{PLAYER}, what’s one thing you wish people understood about your intimacy?",
      "{PLAYER}, what makes you relax enough to let someone in emotionally?",
      "{PLAYER}, what memory of touch still makes your chest tighten softly?",
      "{PLAYER}, what’s the most intimate thing someone could whisper to you?",
      "{PLAYER}, what makes you crave emotional connection more than physical pleasure?",
      "{PLAYER}, when does closeness start to feel overwhelming for you?",
      "{PLAYER}, what’s the most honest moment you’ve ever had while half-dressed?",
      "{PLAYER}, what detail about someone’s body always catches your attention first?",
      "{PLAYER}, how do you like to be comforted after a vulnerable experience?",
      "{PLAYER}, what makes eye contact last longer than you expect?",
      "{PLAYER}, what do you find beautiful about your own body when you slow down to notice it?",
      "{PLAYER}, what makes emotional intimacy turn into desire for you?",
      "{PLAYER}, how do you show someone you trust them with your body?",
      "{PLAYER}, what quiet gesture feels more personal than words?",
      "{PLAYER}, when did you last feel a spark that scared you in a good way?",
      "{PLAYER}, what sensation do you miss the most when you’re alone?",
      "{PLAYER}, what thought can instantly make your heartbeat slow down?",
      "{PLAYER}, what does safety in closeness mean to you?",
      "{PLAYER}, what do you secretly love about being seen in soft light?",
      "{PLAYER}, what makes your confidence bloom when you’re undressed?",
      "{PLAYER}, what kind of warmth between people do you find addictive?",
      "{PLAYER}, what do you wish someone would say to you right before falling asleep together?",
      "{PLAYER}, what’s a fantasy that’s more about trust than about sex?",
      "{PLAYER}, when does emotional honesty start to feel like foreplay?",
      "{PLAYER}, what makes shared vulnerability beautiful to you?",
      "{PLAYER}, what scent, sound, or touch reminds you of home in someone else?",
      "{PLAYER}, what kind of closeness do you crave the most right now?",
      "{PLAYER}, what’s one secret way you like to feel desired without words?"
    ]
  },
  {
    title: "🌞 Nudist-Friendly 🍃",
    items: [
      "{PLAYER}, how different do you feel nude compared to dressed?",
      "{PLAYER}, what part of being nude with others makes you feel most free?",
      "{PLAYER}, what posture feels most natural to you when nude?",
      "{PLAYER}, how does sunlight change how you feel on bare skin?",
      "{PLAYER}, what is your favorite sensation on skin: water, breeze, or touch?",
      "{PLAYER}, what’s the boldest thing you have done nude outside home?",
      "{PLAYER}, what small compliment about your nude body would you love to hear?",
      "{PLAYER}, what is your favorite non-sexual nude activity?",
      "{PLAYER}, if you went to a nude beach with {TARGET}, what would you do first?",
      "{PLAYER}, how does being nude change the way you flirt?",
      "{PLAYER}, what part of your body used to be an insecurity but now you accept?",
      "{PLAYER}, what makes social nudity different from private nudity?",
      "{PLAYER}, what is the best part of walking around with no clothes?",
      "{PLAYER}, do you prefer to tan nude or stay in the shade?",
      "{PLAYER}, what kind of eye contact feels stronger when already nude?",
      "{PLAYER}, how does nudity change the way you sit or move?",
      "{PLAYER}, what’s your favorite way to show confidence when bare?",
      "{PLAYER}, which accessory looks sexier on a nude body: necklace, ring, or anklet?",
      "{PLAYER}, what do you enjoy more nude: swimming, sunbathing, or walking?",
      "{PLAYER}, what part of nudity feels intimate even if not sexual?",
      "{PLAYER}, what everyday action looks better when done naked?",
      "{ALL}, what’s the funniest thing that happened to you while nude?",
      "{PLAYER}, how do you handle nerves the first time you strip in front of others?",
      "{PLAYER}, what’s your towel rule when nude in company?",
      "{PLAYER}, what greeting feels best when nude: hug, handshake, or just a smile?",
      "{PLAYER}, do you prefer full daylight or low light when nude?",
      "{PLAYER}, what makes a nude beach feel safe and fun for you?",
      "{PLAYER}, what ritual after a shower feels best when staying nude?",
      "{PLAYER}, what detail of nudity makes you feel both exposed and powerful?",
      "{PLAYER}, how would you describe your nude body in three words?",
      "{PLAYER}, what’s the best compliment you can give to a nude friend?",
      "{PLAYER}, what’s your favorite part of a nude beach: water, sand, or people?",
      "{PLAYER}, what’s the funniest thing you saw happen at a nude beach?",
      "{PLAYER}, what would you do first when you arrive at a nude resort?",
      "{PLAYER}, what makes camping nude more exciting than normal camping?",
      "{PLAYER}, how do you feel sleeping nude in a tent with others around?",
      "{PLAYER}, what’s the best snack to eat naked under the sun?",
      "{PLAYER}, what activity feels most free when done nude at a resort?",
      "{PLAYER}, what’s the best time of day to be naked at the beach?",
      "{PLAYER}, what game would you play nude in the sand?",
      "{PLAYER}, what part of your body feels best in the ocean nude?",
      "{PLAYER}, what makes a nude pool different from a nude beach?",
      "{PLAYER}, would you join a nude volleyball match or just watch?",
      "{PLAYER}, what’s the boldest outfit you wore before getting naked?",
      "{PLAYER}, what makes a Korean spa (jjimjilbang) exciting when nude?",
      "{PLAYER}, how do you feel walking nude between hot rooms in a spa?",
      "{PLAYER}, what’s the most relaxing nude ritual in a spa?",
      "{PLAYER}, what’s more fun: soaking nude in hot water or sweating in a sauna?",
      "{PLAYER}, what’s your towel trick in a Korean spa?",
      "{PLAYER}, what do you enjoy most after a nude bath: food, nap, or chat?",
      "{PLAYER}, what part of spa nudity feels most intimate but not sexual?",
      "{PLAYER}, how would you explain the feeling of a nude spa to a friend?",
      "{PLAYER}, what’s the best way to break the ice at a nude campfire?",
      "{PLAYER}, would you rather sleep nude in a bungalow or in a tent?",
      "{PLAYER}, what’s more freeing: walking nude at sunrise or sunset?",
      "{PLAYER}, what is your dream location for a nude holiday?",
      "{PLAYER}, how would you decorate a perfect nude resort?",
      "{PLAYER}, what’s more relaxing: nude massage or hot tub?",
      "{PLAYER}, what nude memory would you like to repeat?",
      "{PLAYER}, what would make you laugh the most in a nude camping trip?",
      "{PLAYER}, what is the most surprising thing about sharing a nude spa with strangers?",
      "{PLAYER}, what’s something about being nude that surprised you the first time?",
      "{PLAYER}, what’s a funny or awkward moment you’ve had around nudity?",
      "{PLAYER}, how would you explain to a friend why social nudity feels natural?",
      "{PLAYER}, what do you enjoy most about relaxing nude with friends?",
      "{ALL}, what’s one simple rule everyone should follow in a nude space?",
      "{PLAYER}, what’s your favorite way to make newcomers feel comfortable in a nude setting?",
      "{PLAYER}, what do you think people misunderstand most about nudism?",
      "{PLAYER}, how would you describe the feeling of being comfortable in your own skin?",
      "{PLAYER}, what’s a small act of kindness that feels different when you’re nude?",
      "{PLAYER}, what moment made you realize nudity can be normal and peaceful?",
      "{PLAYER}, what makes sharing a nude activity with friends feel special?",
      "{PLAYER}, what do you wish more people understood about body comfort?",
      "{PLAYER}, how do you handle questions about nudism from curious friends?",
      "{PLAYER}, what’s a funny myth about nudists that always makes you laugh?",
      "{PLAYER}, how do you usually break the ice in a nude group activity?",
      "{PLAYER}, what’s the best advice you’d give to someone nervous about their first nude experience?",
      "{PLAYER}, what makes you feel safe in a nudist environment?",
      "{PLAYER}, what’s a family-friendly nude activity you’ve heard of or tried?",
      "{ALL}, what’s one thing that makes a nude day out feel truly free?",
      "{PLAYER}, what’s your go-to gesture of friendliness when everyone’s nude?",
      "{PLAYER}, what would make a mixed group (friends, family, newcomers) feel at ease together nude?",
      "{PLAYER}, what’s a little ritual you have before joining a nude event?",
      "{PLAYER}, what detail makes you feel the most at home in a nudist resort?",
      "{PLAYER}, what’s a common fear people have before their first nude day that turns out fine?",
      "{PLAYER}, what’s a memory of laughter you associate with nudity?",
      "{PLAYER}, how has being nude among others changed how you see your own body?",
      "{PLAYER}, what simple thing reminds you that nudity is just normal?",
      "{PLAYER}, what’s something that always feels wholesome and freeing about nudity?",
      "{PLAYER}, what makes you feel accepted when nude in a group?",
      "{PLAYER}, what would you tell someone who thinks nudity always has to be sexual?",
      "{PLAYER}, what part of social nudity makes you laugh the most?",
      "{PLAYER}, what kind of place would make a great first nude experience for beginners?",
      "{ALL}, what makes a nude group activity memorable without being awkward?"
    ]
  },
  {
    title: "🌍 Culture & Curiosity 🎶",
    items: [
      "{PLAYER}, what food from home do you want everyone here to taste once?",
      "{PLAYER}, what do visitors often get wrong about your city or region?",
      "{ALL}, breakfast team: sweet or savory?",
      "{PLAYER}, shoes at home: on or off where you live?",
      "{PLAYER}, dinner time where you are: early or late?",
      "{PLAYER}, how do people greet friends vs strangers in your country?",
      "{PLAYER}, teach us the word for 'cheers' in your language.",
      "{PLAYER}, what hand gesture has a different meaning in other places?",
      "{PLAYER}, what small rule do tourists often miss in your area?",
      "{PLAYER}, what sound or smell instantly says 'home' to you?",
      "{PLAYER}, public transport or car: what do people use most where you are?",
      "{ALL}, coffee or tea to start the day?",
      "{PLAYER}, what holiday or festival makes your town feel alive?",
      "{PLAYER}, what childhood game does almost everyone know where you grew up?",
      "{PLAYER}, what is your comfort food when you feel homesick?",
      "{PLAYER}, what time do shops usually close in your city?",
      "{PLAYER}, tipping where you live: always, sometimes, or rarely?",
      "{PLAYER}, how close do people stand when talking in your country?",
      "{PLAYER}, public hugging: normal or rare where you are?",
      "{PLAYER}, sauna/spa/beach culture: common or not where you live?",
      "{PLAYER}, teach one polite phrase in your language we can use tonight.",
      "{PLAYER}, what stereotype about your people is partly true?",
      "{PLAYER}, what stereotype about your people is unfair?",
      "{PLAYER}, what local dish sounds strange but tastes great?",
      "{PLAYER}, what do people wear at home that might look odd elsewhere (e.g., house shoes)?",
      "{PLAYER}, what is a sign of good manners in your culture?",
      "{PLAYER}, small talk with strangers: common or not where you live?",
      "{PLAYER}, public kissing or hand-holding: normal or not?",
      "{PLAYER}, what place of nature near you should we visit one day?",
      "{PLAYER}, which units do you think in: °C or °F? km or miles?",
      "{PLAYER}, what is the go-to late-night food in your city?",
      "{PLAYER}, what snack do you bring to the beach or park?",
      "{PLAYER}, what funny translation fail have you seen online or in real life?",
      "{PLAYER}, what word from your language has no good English translation?",
      "{PLAYER}, how do people handle heat or cold where you live (siesta, sauna, layers)?",
      "{PLAYER}, what public rule is strict where you are (queues, noise, recycling)?",
      "{ALL}, what is one tiny habit from your culture you are proud of?",
      "{PLAYER}, what book changed the way you see the world?",
      "{PLAYER}, what movie or series best captures your culture’s spirit?",
      "{PLAYER}, what kind of art moves you the most — painting, music, film, or something else?",
      "{PLAYER}, which country’s music makes you feel something deep even if you don’t know the language?",
      "{PLAYER}, what story from your childhood still feels magical today?",
      "{PLAYER}, what kind of humor defines people where you live?",
      "{PLAYER}, what local song or artist deserves to be famous worldwide?",
      "{PLAYER}, what foreign dish became part of your comfort food?",
      "{PLAYER}, what book or movie from another culture taught you something about yourself?",
      "{PLAYER}, what cultural tradition from elsewhere do you secretly admire?",
      "{PLAYER}, what stereotype about your culture do you wish people would drop?",
      "{PLAYER}, what moment from a movie or show always gives you chills?",
      "{PLAYER}, what kind of theater or live performance do you enjoy the most?",
      "{PLAYER}, what author, musician, or artist represents your country best?",
      "{PLAYER}, what foreign word do you wish existed in your language?",
      "{PLAYER}, what kind of film genre feels most “you” — drama, comedy, thriller, or romance?",
      "{PLAYER}, what cultural custom surprised you the most when you learned about it?",
      "{PLAYER}, what city or country’s style (fashion, art, design) inspires you the most?",
      "{PLAYER}, what do people from your culture do when they want to show affection?",
      "{PLAYER}, what kind of festival would you create if you could?",
      "{PLAYER}, what is one tradition from another culture you’d love to experience firsthand?",
      "{PLAYER}, what’s a common movie trope in your country that makes you laugh?",
      "{PLAYER}, what story or myth from your culture should everyone hear once?",
      "{PLAYER}, what historical figure from your country would you invite to dinner?",
      "{PLAYER}, what kind of music best fits your everyday mood?",
      "{PLAYER}, what’s a book you think everyone here should read?",
      "{PLAYER}, how do people in your area express sadness or joy publicly?",
      "{PLAYER}, what painting, film, or song feels like “home” to you?",
      "{PLAYER}, what country or culture do you think you would blend into easily?",
      "{PLAYER}, what small daily habit feels very “your culture” to you?",
      "{PLAYER}, what international movie or series should be watched in the original language?",
      "{PLAYER}, what cuisine outside your own always feels like a treat?",
      "{PLAYER}, what travel experience changed how you see your own country?",
      "{PLAYER}, what foreign custom seems strange but charming to you?",
      "{PLAYER}, what museum, monument, or landmark left a deep impression on you?",
      "{PLAYER}, what would surprise people most about your country’s pop culture?",
      "{PLAYER}, what kind of storytelling (books, oral tales, comics) do people enjoy most where you live?",
      "{ALL}, if you could swap cultures for one week, where would you go and why?"
    ]
  },
 {
    title: "⚡ QuickPick ⚡",
    items: [
      "{PLAYER}: Sweet or salty?",
      "{PLAYER}: Morning or night?",
      "{PLAYER}: Beach or mountains?",
      "{PLAYER}: Coffee or tea?",
      "{PLAYER}: Hot or cold shower?",
      "{PLAYER}: Hug or handshake?",
      "{PLAYER}: Texting or calling?",
      "{PLAYER}: Dogs or cats?",
      "{PLAYER}: Introvert or extrovert?",
      "{PLAYER}: Book or movie?",
      "{PLAYER}: Sneakers or barefoot?",
      "{PLAYER}: Smile or eyes first?",
      "{PLAYER}: Loud laugh or shy smile?",
      "{PLAYER}: Sweet talk or teasing?",
      "{PLAYER}: Compliment or joke?",
      "{PLAYER}: Slow build or fast spark?",
      "{PLAYER}: Curious or shy?",
      "{PLAYER}: First notice: voice or body?",
      "{PLAYER}: Long chat or short glance?",
      "{PLAYER}: Being admired or understood?",
      "{PLAYER}: Words or body language?",
      "{PLAYER}: Playful or serious?",
      "{PLAYER}: Eye contact or touch?",
      "{PLAYER}: Whisper or stare?",
      "{PLAYER}: Hold close or stay apart?",
      "{PLAYER}: Watch or be watched?",
      "{PLAYER}: Tease or be teased?",
      "{PLAYER}: Rough or slow?",
      "{PLAYER}: Lights on or lights off?",
      "{PLAYER}: Moan or whisper?",
      "{PLAYER}: Control or surrender?",
      "{PLAYER}: Kiss or bite?",
      "{PLAYER}: Top or bottom?",
      "{PLAYER}: Touch or talk?",
      "{PLAYER}: Alone or with audience?",
      "{PLAYER}: Naked truth or sexy lie?",
      "{PLAYER}: Public fantasy or private secret?",
      "{PLAYER}: Trust or lust?",
      "{PLAYER}: Laugh or blush?",
      "{PLAYER}: Eyes open or closed?",
      "{PLAYER}: Silent desire or loud passion?",
      "{PLAYER}: Sauna or shower?",
      "{PLAYER}: Sun on skin or breeze on skin?",
      "{PLAYER}: Swim nude or sunbathe nude?",
      "{PLAYER}: Hug nude or sit nude?",
      "{PLAYER}: Towel or no towel?",
      "{PLAYER}: Daylight nude or night nude?",
      "{PLAYER}: First nude step: fast or slow?",
      "{PLAYER}: Beach or forest nudity?",
      "{PLAYER}: Necklace or nothing?",
      "{PLAYER}: Sweet or spicy nude moment?",
      "{PLAYER}: Pizza or pasta?",
      "{PLAYER}: Wine or beer?",
      "{PLAYER}: Europe or America trip?",
      "{PLAYER}: Train or plane?",
      "{PLAYER}: Early dinner or late dinner?",
      "{PLAYER}: Learn slang or learn food?",
      "{PLAYER}: Tradition or modern?",
      "{PLAYER}: Public hug or private smile?",
      "{PLAYER}: Share or keep secret?"
    ]
  },
 {
    title: "🔥 DARE 🔥",
    items: [
      "{PLAYER}, stand up and do a slow 360 spin for the camera.",
      "{PLAYER}, blow a kiss to the camera with both hands.",
      "{PLAYER}, hold eye contact with the camera for 10 seconds without smiling.",
      "{PLAYER}, flex or pose your body like you are on a nude beach photo shoot.",
      "{PLAYER}, lie down so the camera shows your whole body for 15 seconds.",
      "{PLAYER}, turn around and show your backside to the camera.",
      "{PLAYER}, stretch your arms over your head and hold for 10 seconds.",
      "{PLAYER}, act like you are rubbing sunscreen on your chest or shoulders.",
      "{PLAYER}, crawl closer to the camera and smile.",
      "{PLAYER}, slowly drink water (or your drink) while staring at the camera.",
      "{PLAYER}, whisper something naughty to the camera.",
      "{PLAYER}, do your sexiest walk across the room and back.",
      "{PLAYER}, close your eyes and touch your lips slowly for 5 seconds.",
      "{PLAYER}, show your favorite body part proudly for 10 seconds.",
      "{PLAYER}, pretend you are tanning and adjust your body for the best angle.",
      "{PLAYER}, moan quietly once, like a secret slipped out.",
      "{PLAYER}, pretend you are about to kiss the camera screen.",
      "{PLAYER}, give your best fake “porn star” pose for 10 seconds.",
      "{PLAYER}, use your towel (or pillow) as if it was a dance partner.",
      "{PLAYER}, turn the lights brighter or dimmer to change the mood.",
      "{PLAYER}, sit with your legs open for 5 seconds.",
      "{PLAYER}, slap your own butt once and wink.",
      "{PLAYER}, slowly run your hand down your body until it goes off camera.",
      "{PLAYER}, tease the camera by hiding under the towel and pulling it away again.",
      "{PLAYER}, show the funniest nude pose you can think of.",
      "{PLAYER}, lick your lips slowly while looking into the camera.",
      "{PLAYER}, lean in very close to the camera and say one sexy word.",
      "{PLAYER}, arch your back like you’re stretching in bed.",
      "{PLAYER}, strike your best “statue” nude pose and hold it.",
      "{PLAYER}, mime putting suntan lotion on your butt."
    ]
  }
];

if (Array.isArray(window.QUESTION_DATA)) {
  window.QUESTION_DATA.forEach((category) => {
    if (category && typeof category === 'object') {
      Object.freeze(category.items);
      Object.freeze(category);
    }
  });
  Object.freeze(window.QUESTION_DATA);
}
